spring:
  application:
    name: birdbook-api
  profiles:
    active: #spring.profiles.active#
    default: dev
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  liquibase:
    change-log: "classpath:db/master.xml"

feign:
  url: https://exapmle.com