spring:
  application:
    name: birdbook-api
  profiles:
    active: #spring.profiles.active#
    default: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  liquibase:
    change-log: "classpath:db/master.xml"

feign:
  url: https://exapmle.com