spring:
  config:
    profiles:
      active: dev

  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 10MB
#Yyj188706
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/witchtalk?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password:  rootroot
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false

server:
  port: 8080

application:
  client_id: 495ce33da2f8252
  client_secret: e8c197682360944a96322dd2aef0f3a6a194db8f
  auth_url: https://api.imgur.com/oauth2/authorize
  token_url: https://api.imgur.com/oauth2/token
jwt:
  secret: 9GItnI6fFFe9Xy8H83nknT7sUL2NmTFqKMYA9zcK9lXgtYvfSwplsUtKPPO9jRw2TrZryP/vZ7ghNfaJNdwuvzQcEMzytNa2CfFQN1mwQH1pUneyXTpvv5evZGmdqGIBc/VLKCf7lYgQQcf7KqCcbeiBTCWphaet2t6xIMJ6LDFJy8U1vnun0DYM6AQ/uhAPCmfK6TnfhBITV7imW/sKOFoDMBYV46yQkD+pTg==
  expirationInMs: 2592000000 #30 days

