spring:
  config:
    profiles:
      active: prod

  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 10MB

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://prodorderit-db-prod.cxhsa0mcirho.eu-west-1.rds.amazonaws.com:3306/OrderitProd?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ProdOrderIT
    password: z^-J1p-t2RkL^JPko=q1IFR78b95.t
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false

server:
  port: 8080

application:
  s3-info:
    bucket-name: prod-orderit
  app-url: "https://app.orderit.ie"
  server-email: "support@orderit.ie"
  order-email: "orders@orderit.ie"
  company-register-email: 'bin.li@orderit.ie'
  internal-company-id: 8
  internal-supplier-test-email: demo-supplier@orderit.ie

jwt:
  secret: 9GItnI6fFFe9Xy8H83nknT7sUL2NmTFqKMYA9zcK9lXgtYvfSwplsUtKPPO9jRw2TrZryP/vZ7ghNfaJNdwuvzQcEMzytNa2CfFQN1mwQH1pUneyXTpvv5evZGmdqGIBc/VLKCf7lYgQQcf7KqCcbeiBTCWphaet2t6xIMJ6LDFJy8U1vnun0DYM6AQ/uhAPCmfK6TnfhBITV7imW/sKOFoDMBYV46yQkD+pTg==
  expirationInMs: 2592000000 #30 days

feign:
  caf:
    url: https://api.caf.mycloudpa-qa.com
    token: aa5d758e764645a6bd677916eac773014b60125d9abf4838a348c50bad1810ac
  buyTillRolls:
    url: https://api.buyTillRolls.mycloudpa.com
    token: aa5d758e764645a6bd677916eac773014b60125d9abf4838a348c50bad1810ac
  pureoil:
    url: https://api.pureoil.mycloudpa.com
    token: aa5d758e764645a6bd677916eac773014b60125d9abf4838a348c50bad1810ac